### ISSUE TITLE
Mismatch with DCS

### ISSUE THREAD

**Issue by avinashvarna** [sanskrit-coders/dcs-scraper#2]
There are significant errors in the data returned by the API. A particularly egregious example is http://vedavaapi.org:5984/dcs_sentences/sentence_100003 which returns:
```javascript
{
  "_id": "sentence_100003",
  "_rev": "1-403809ccc0220f2c6c0331536bac5a2b",
  "dcsId": 100003,
  "dcsAnalysisDecomposition": [
    [
      {
        "dcsGrammarHint": "[n.s.n.]",
        "dcsId": 71929,
        "root": "rūpa"
      }
    ],
    [
      {
        "dcsGrammarHint": "[l.p.m.]",
        "dcsId": 37875,
        "root": "tad"
      }
    ],
    [
      {
        "dcsGrammarHint": "[3. sg. Fut.]",
        "dcsId": 157250,
        "root": "bhū"
      }
    ]
  ],
  "jsonClass": "DcsSentence",
  "text": "rūpamārogyamaiśvaryaṃ teṣvanantaṃ bhaviṣyati // (17.2)"
}
```
whereas on the DCS website:
```
rūpamārogyamaiśvaryaṃ teṣvanantaṃ bhaviṣyati // (17.2)
rūpa [n.s.n.]-ārogya [n.s.n.]-aiśvarya [n.s.n.]  tad [l.p.m.]-ananta [n.s.n.]  bhū [3. sg. Fut.]
```
About half the decomposition is missing. Either there is a bug in the scraper, or the DCS database has been (significantly) improved since it was last scraped. In either case, it would be useful to update the database. If it is the latter, it would be nice to also have a plan to periodically update the database at some TBD frequency.

**Comment by vvasuki** [comment]
Confirmed and fixed the bug in my scraper. Will fix the database and update this thread.

**Comment by vvasuki** [comment]
All updated.

**Comment by avinashvarna** [comment]
अनुगृहीता वयम् ।
